Indentation error
snipcart/vue-blog-demo pull request #19
Opened 2020-08-26 04:59 UTC by Samyak-Shreyash

An indentation error @ Line52 in the matchmedia.js file in plugins located in the source directory was resulting in improper compilation of file.

2020-08-26 14:27 UTC, JeanSebTr requested changes
Hi @Samyak-Shreyash !

You seem to have added a new file instead of fixing the original, can you fix your PR?


Thanks

2020-09-04 15:43 UTC, udyux commented
@JeanSebTr Just `npm run lint` and you're good to go. I dont have permission to push new branches but it's a quick fix.

2020-09-25 07:29 UTC, Aamirpal commented
> Hi @Samyak-Shreyash !
> 
> You seem to have added a new file instead of fixing the original, can you fix your PR?
> 
> Thanks

Hey @Samyak-Shreyash : 
All you need to provide **approprite space** at **line:52** and we are golden :star_struck: 

**Ref:** 
_**const operand = (!limit) ? '=='
      : (limit === 'min') ? '<'
        : '>'**_

2022-06-10 16:23 UTC, pixerize commented
Hello, I really love this demo and I am new to Vue.js, I would like to build it locally to understand better how it works. 
Npm install cannot complete. What can I do to make it run :)

Or even better if anyone has it created in the newer version of Vue. 

Thanks

2025-12-19 15:09 UTC, closed without merging